### ISSUE TITLE
How do I save the network parameters of Policy and Cost Q-Function Encemble at the end of the training？

### ISSUE THREAD

**Issue by zsn2021** [ZifanWu/CAL#1]
Hello, thank you for your work. I tested on the local computer and encountered a problem. How do I save the network parameters of Policy and Cost Q-Function Encemble at the end of the training?

**Comment by ZifanWu** [comment]
Hi @zsn2021! Thank you for your interest in our work. I've added save&load modules to the main branch. To save the network parameters of the policy and value functions, just add `--save_parameters` in your command line when initiating a run.
